import { noteFilename, noteToMarkdown } from "@/lib/notes/render";
import type { ClinicalNote } from "@/lib/notes/types";

export type NoteExportFormat = "markdown" | "docx" | "pdf";

function fmtDate(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleString(undefined, {
        year: "numeric",
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      });
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Give the browser a tick to start the download before revoking.
  setTimeout(() => URL.revokeObjectURL(url), 1_000);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------

export function exportMarkdown(note: ClinicalNote) {
  const blob = new Blob([noteToMarkdown(note)], {
    type: "text/markdown;charset=utf-8",
  });
  downloadBlob(blob, `${noteFilename(note)}.md`);
}

// ---------------------------------------------------------------------------
// DOCX — `docx` is dynamically imported so it stays out of the page's initial
// bundle and only loads when the user actually exports a Word document.
// ---------------------------------------------------------------------------

export async function exportDocx(note: ClinicalNote) {
  const { Document, HeadingLevel, Packer, Paragraph, TextRun } = await import(
    "docx"
  );

  const heading = (text: string) =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_2 });
  const para = (text: string) =>
    new Paragraph({ children: [new TextRun(text)] });
  const bullet = (text: string) =>
    new Paragraph({ children: [new TextRun(text)], bullet: { level: 0 } });
  const labelled = (label: string, value: string) =>
    new Paragraph({
      bullet: { level: 0 },
      children: [
        new TextRun({ text: `${label}: `, bold: true }),
        new TextRun(value),
      ],
    });

  const body: InstanceType<typeof Paragraph>[] = [
    new Paragraph({ text: "Clinical Note", heading: HeadingLevel.TITLE }),
  ];
  if (note.patientSummary) {
    body.push(
      new Paragraph({ children: [new TextRun({ text: note.patientSummary, italics: true })] })
    );
  }

  if (note.presentingComplaints.length) {
    body.push(heading("Presenting complaints"));
    note.presentingComplaints.forEach((c) => body.push(bullet(c)));
  }
  if (note.history) {
    body.push(heading("History of presenting complaint"), para(note.history));
  }
  if (note.pastHistory) {
    body.push(heading("Past medical & surgical history"), para(note.pastHistory));
  }
  if (note.medications.length) {
    body.push(heading("Medications"));
    note.medications.forEach((m) => body.push(bullet(m)));
  }
  if (note.socialFamilyHistory) {
    body.push(heading("Social & family history"), para(note.socialFamilyHistory));
  }

  const exam = note.examination;
  if (exam.general || exam.vitals.length || exam.systems.length) {
    body.push(heading("Examination"));
    if (exam.general) body.push(para(exam.general));
    exam.vitals.forEach((v) => body.push(labelled(v.label, v.value)));
    exam.systems.forEach((s) => body.push(labelled(s.name, s.findings)));
  }

  if (note.investigations.length) {
    body.push(heading("Investigations"));
    note.investigations.forEach((i) => body.push(bullet(i)));
  }
  if (note.assessment) {
    body.push(heading("Assessment"), para(note.assessment));
  }
  if (note.plan.length) {
    body.push(heading("Plan"));
    note.plan.forEach((p) => body.push(bullet(p)));
  }
  if (note.recommendations.length) {
    body.push(heading("Recommendations (AI-suggested)"));
    note.recommendations.forEach((r) => body.push(bullet(r)));
  }

  body.push(
    new Paragraph({
      spacing: { before: 300 },
      children: [
        new TextRun({
          text:
            `Generated by ${note.modelName} · ${fmtDate(note.completedAt)}` +
            (note.source === "synthesised"
              ? " · synthesised from structured findings"
              : ""),
          color: "888888",
          size: 18,
        }),
      ],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "AI-generated draft — review before clinical use.",
          color: "888888",
          size: 18,
          italics: true,
        }),
      ],
    })
  );

  const doc = new Document({ sections: [{ children: body }] });
  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, `${noteFilename(note)}.docx`);
}

// ---------------------------------------------------------------------------
// PDF — render a self-contained print document and hand it to the browser's
// "Save as PDF". Avoids a heavy PDF dependency and reuses the print pipeline.
// ---------------------------------------------------------------------------

function noteToPrintHtml(note: ClinicalNote): string {
  const esc = escapeHtml;
  const section = (title: string, inner: string) =>
    inner ? `<h2>${esc(title)}</h2>${inner}` : "";
  const list = (items: string[]) =>
    items.length
      ? `<ul>${items.map((i) => `<li>${esc(i)}</li>`).join("")}</ul>`
      : "";
  const prose = (text: string) => (text ? `<p>${esc(text)}</p>` : "");

  const exam = note.examination;
  const examInner =
    prose(exam.general) +
    (exam.vitals.length
      ? `<ul>${exam.vitals
          .map((v) => `<li><strong>${esc(v.label)}:</strong> ${esc(v.value)}</li>`)
          .join("")}</ul>`
      : "") +
    (exam.systems.length
      ? `<ul>${exam.systems
          .map((s) => `<li><strong>${esc(s.name)}:</strong> ${esc(s.findings)}</li>`)
          .join("")}</ul>`
      : "");

  return `<!doctype html><html><head><meta charset="utf-8"><title>Clinical Note</title>
<style>
  @page { margin: 22mm 18mm; }
  * { box-sizing: border-box; }
  body { font-family: Georgia, "Times New Roman", serif; color: #111; line-height: 1.5; max-width: 720px; margin: 0 auto; padding: 24px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .summary { font-style: italic; color: #333; margin: 0 0 18px; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: .06em; color: #444; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin: 22px 0 8px; }
  p { margin: 0 0 8px; }
  ul { margin: 0 0 8px; padding-left: 20px; }
  li { margin: 2px 0; }
  .meta { margin-top: 28px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 11px; color: #888; }
</style></head><body>
  <h1>Clinical Note</h1>
  ${note.patientSummary ? `<p class="summary">${esc(note.patientSummary)}</p>` : ""}
  ${section("Presenting complaints", list(note.presentingComplaints))}
  ${section("History of presenting complaint", prose(note.history))}
  ${section("Past medical & surgical history", prose(note.pastHistory))}
  ${section("Medications", list(note.medications))}
  ${section("Social & family history", prose(note.socialFamilyHistory))}
  ${section("Examination", examInner)}
  ${section("Investigations", list(note.investigations))}
  ${section("Assessment", prose(note.assessment))}
  ${section("Plan", list(note.plan))}
  ${section("Recommendations (AI-suggested)", list(note.recommendations))}
  <div class="meta">
    Generated by ${esc(note.modelName)} · ${esc(fmtDate(note.completedAt))}${
      note.source === "synthesised" ? " · synthesised from structured findings" : ""
    }<br>AI-generated draft — review before clinical use.
  </div>
</body></html>`;
}

/** Returns false when a popup blocker prevented the print window. */
export function exportPdf(note: ClinicalNote): boolean {
  const w = window.open("", "_blank", "width=820,height=1000");
  if (!w) return false;
  w.document.write(noteToPrintHtml(note));
  w.document.close();
  w.focus();
  // Let layout settle before invoking the print dialog.
  setTimeout(() => w.print(), 250);
  return true;
}

export function exportNote(note: ClinicalNote, format: NoteExportFormat): boolean | void {
  if (format === "markdown") return exportMarkdown(note);
  if (format === "docx") return void exportDocx(note);
  if (format === "pdf") return exportPdf(note);
}
