import type { ClinicalNote } from "@/lib/notes/types";

/** Sections in document order, with their display headings. */
export const NOTE_SECTIONS = [
  "Presenting complaints",
  "History of presenting complaint",
  "Past medical & surgical history",
  "Medications",
  "Social & family history",
  "Examination",
  "Investigations",
  "Assessment",
  "Plan",
  "Recommendations",
] as const;

function fmtDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

const bullets = (items: string[]) => items.map((i) => `- ${i}`).join("\n");

/** Render a note as GitHub-flavoured Markdown. */
export function noteToMarkdown(note: ClinicalNote): string {
  const out: string[] = [];
  out.push("# Clinical Note");
  if (note.patientSummary) out.push(`_${note.patientSummary}_`);

  if (note.presentingComplaints.length) {
    out.push("## Presenting complaints", bullets(note.presentingComplaints));
  }
  if (note.history) out.push("## History of presenting complaint", note.history);
  if (note.pastHistory) out.push("## Past medical & surgical history", note.pastHistory);
  if (note.medications.length) out.push("## Medications", bullets(note.medications));
  if (note.socialFamilyHistory) {
    out.push("## Social & family history", note.socialFamilyHistory);
  }

  const exam = note.examination;
  if (exam.general || exam.vitals.length || exam.systems.length) {
    const parts: string[] = ["## Examination"];
    if (exam.general) parts.push(exam.general);
    if (exam.vitals.length) {
      parts.push(exam.vitals.map((v) => `- **${v.label}:** ${v.value}`).join("\n"));
    }
    if (exam.systems.length) {
      parts.push(exam.systems.map((s) => `- **${s.name}:** ${s.findings}`).join("\n"));
    }
    out.push(parts.join("\n\n"));
  }

  if (note.investigations.length) out.push("## Investigations", bullets(note.investigations));
  if (note.assessment) out.push("## Assessment", note.assessment);
  if (note.plan.length) out.push("## Plan", bullets(note.plan));
  if (note.recommendations.length) {
    out.push(
      "## Recommendations (AI-suggested)",
      bullets(note.recommendations)
    );
  }

  out.push(
    "---",
    `Generated by ${note.modelName} · ${fmtDate(note.completedAt)}` +
      (note.source === "synthesised"
        ? " · synthesised from structured findings"
        : "") +
      "\nAI-generated draft — review before clinical use."
  );

  return out.join("\n\n") + "\n";
}

/** Plain-text rendering for clipboard. */
export function noteToPlainText(note: ClinicalNote): string {
  return noteToMarkdown(note)
    .replace(/^#+\s*/gm, "")
    .replace(/\*\*/g, "")
    .replace(/^_|_$/gm, "");
}

/** A filename stem like "clinical-note-2026-06-30". */
export function noteFilename(note: ClinicalNote): string {
  const d = new Date(note.completedAt);
  const stamp = Number.isNaN(d.getTime())
    ? "note"
    : d.toISOString().slice(0, 10);
  return `clinical-note-${stamp}`;
}
